import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sophomore course project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>
      </Navbar>

      <main className={styles.main}>
        <h1 className={styles.title}>All my Sophomore course projects !</h1>
        <p className={styles.description}>
          This is a collection of all my sophomore course projects from LearnWeb3DAO.
        </p>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
